#! /bin/bash
# Copyright (c) 1996-2012 My Company.
# All rights reserved.
#
# Author: Bob Bobson, 2012
#
# Please send feedback to bob@bob.com
#
# /etc/init.d/smartclock
#
### BEGIN INIT INFO
# Provides: smartclock
# Required-Start: 
# Should-Start: 
# Required-Stop: 
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Smart Alarmclock
# Description:    Reads events from calendar and sets alarm.
### END INIT INFO

# Activate the python virtual environment
#    . /path_to_virtualenv/activate

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    python /usr/local/lib/python2.7/dist-packages/smartclock/main.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /usr/local/lib/python2.7/dist-packages/smartclock/main.py stop
    ;;
  restart)
    echo "Restarting server"
    python /usr/local/lib/python2.7/dist-packages/smartclock/main.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/smartclock.sh {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0